(define (main)
        (setPort (open (getElement ScamArgs 1) 'read))
        (define func (eval (readExpr) this))
        (define arg (readExpr))
        (println "(S <function anonymous(x)> " arg ") is " (fmt "%.15f" (real (S func arg) )))
        (println "(w <function anonymous(x)> " arg ") is "  (fmt "%.15f" (real (w func arg))))
) 

(define (w func num) 
    (cond
        ((!= num 0) 
            (define s (real (S func (real num))))
            (define Sp1 (real (S func (+ num 1.0))))
            (define Sm1 (real (S func (- num 1.0))))
            (real ( / 
                (real (- (* Sp1 Sm1) (* s s)))
                (real (+ Sp1 (+ Sm1 (* -2 s))))
            ))
        )
        (else (real (func num)))
    )
)

(define (S func n)
    (define (iter i sum)
        (cond 
            ((<= i n)
                (real (iter (+ i 1) (+ sum (func i)) ))
            )
            (else sum)
        )
    )
    (real (iter 0 0))
)
