(define (main)
    (setPort (open (getElement ScamArgs 1) 'read))
    (apply pt (readExpr))
)

(define (pt n)
	(define (printNums rows cols)
		(if (or (> rows cols) (= rows cols)) (print (pasT rows cols)))
		(if (!= rows cols)  (printSpaces 1))
		(if (> rows cols) (printNums rows (+ cols 1)))
	)
	(define (printTheLine rows)
		(if (< rows n)
			(begin
				(printSpaces (- n (+ rows 1)))
				(printNums rows 0)
				(print "\n")
				(printTheLine (+ rows 1))
			)
		)
	)
	(define (printSpaces rows)
		(if (> rows 0) (print " "))
		(if (> rows 0) (printSpaces (- rows 1)))
	)
	(define (pasT rows cols)
		(cond
			((or (= 0 cols) (= rows cols)) 1)
			(else (+ (pasT ( - rows 1) cols)
				  (pasT (- rows 1) (- cols 1)))
			)
		)
	)
	(printTheLine 0)
)
