(define (main)
        (setPort (open (getElement ScamArgs 1) 'read))
        (define env this)
        (define (iter expr)
            (if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
        )
        (iter (readExpr))
        (env)
)

(define (replace func args)
    (define body (get 'code func))
    (define params (get 'parameters func))
    (define (iter code)
        (cond 
            ((null? code) code)
            ((object? code) code)
            ((atom? (car code)) 
                (if (not (null? (in? (car code) args)))
                    (set-car! code (in? (car code) args))
                )
                (iter (cdr code))
            )
            (else (iter (car code)) (iter (cdr code)))
        )
    )
    (define (in? code arg)
        (cond
            ((nil? arg) nil)
            ((null? code) nil)
            ((equal? code (car arg)) 
                (car (cdr arg))
            )
            (else (in? code (cddr arg)))
        )
    )
    (iter body)
    (iter params)
    ;(set 'code (iter body) func)
)
